    StartupEvents.registry("block", (block) => {
        //Start Casing
        block.create("start_casing")
        .displayName("Start Casing")
        .material("wood")
        .hardness(2.0)
        .resistance(2.0)
        .tagBlock("mekaminers:custom_casings")
        .requiresTool(true) 
        .tagBlock("mineable/axe")
        .tagBlock("mineable/pickaxe")
        .tagBlock('minecraft:needs_iron_tool')
        //Started Casing 
        block.create("started_casing")
        .displayName("Started Casing")
        .material("wood")
        .hardness(2.0)
        .resistance(2.0)
        .tagBlock("mekaminers:custom_casings")
        .requiresTool(true) 
        .tagBlock("mineable/axe")
        .tagBlock("mineable/pickaxe")
        .tagBlock('minecraft:needs_iron_tool') 
    })
